datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/postgres
  username: postgres
  password: postgres
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8001